### ISSUE TITLE
Doesn't appear to work

### ISSUE THREAD

**Issue by SheepCommander** [Twizzer/relationship-notifier#3]
Nothing happens when someone unfriends me

**Comment by Twizzer** [comment]
When you leave a server do you get the notification that you've been kicked from the server?

**Comment by SheepCommander** [comment]
Nope

**Comment by Twizzer** [comment]
Unable to reproduce. Closed for no additional info after months of testing.

**Comment by SheepCommander** [comment]
Damn sorry but I just now installed Powercord & your plugin and I still don't get the notif (or maybe it doesn't show up because of Discord's new "Why did you leave" feature)

**Comment by SheepCommander** [comment]
Cloud install of win11

**Comment by Twizzer** [comment]
Operating system doesn't affect the plugins as they hook into the powercord system built on discord canary. Operating system has no effect on the plugins. I have tested repeatedly and can't reproduce your issues. I get notifications when kicked from servers/leaving servers as well as when someone removes me from friends.

Try deleting the plugin and redownloading or unloading and reloading Powercord. I've asked several people who use this plugin and no other party is reporting the issues you have.

**Comment by SheepCommander** [comment]
Can you upload a Screenshot of the notification I'm supposed to see?

**Comment by SheepCommander** [comment]
Hey! Friend notif works but I don't get any notif when I leave, I'll quickly try seeing if there's a notif when I actually get kicked/banned
![image](https://user-images.githubusercontent.com/66646514/160306000-a3d649dd-3503-4930-91a6-5f331d774097.png)

**Comment by SheepCommander** [comment]
I do! 
![image](https://user-images.githubusercontent.com/66646514/160306077-b2212a94-f6ce-4cd9-bef3-40b327beba91.png)

Sorry to bother you

**Comment by SheepCommander** [comment]
It works! sorry

**Comment by Twizzer** [comment]
Glad we resolved this issue for you. Closing since this has been resolved.
