### ISSUE TITLE
Suggestion - Add server owner name, and user IDs

### ISSUE THREAD

**Issue by IveMalfunctioned** [Twizzer/relationship-notifier#4]
Whenever someone removes you, their user ID should be included
When you get banned or kicked from a group chat or server, the owner's name/tag and user ID should be included
There should also be a button to DM the owner/who removed you
Similar to the BetterDiscord plugin GuildAndFriendRemovalAlerts

**Comment by Twizzer** [comment]
If you have a plugin that works a specific way you enjoy, I'd suggest that you download BDCompat for Powercord and use that Plugin.
